apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-platform

resources:
  - namespace.yaml
  # Open WebUI
  - open-webui/pvc.yaml
  - open-webui/service.yaml
  - open-webui/secret.yaml
  - open-webui/deployment.yaml
  - open-webui/ingress.yaml
  # OpenClaw
  - openclaw/pvc.yaml
  - openclaw/postgres.yaml
  - openclaw/secret.yaml
  - openclaw/service.yaml
  - openclaw/deployment.yaml
  - openclaw/ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: ai-platform
  app.kubernetes.io/managed-by: kustomize
